### ISSUE TITLE
Custom Events documentation link broken

### ISSUE THREAD

**Issue by ankit-saxena** [BranchMetrics/documentation#135]
The Custom Event documentation link referenced here : https://dev.branch.io/recipes/dashboard_pro_tips/#funnels  is broken. Need to be updated for respective SDKs.
Android: https://dev.branch.io/references/android_sdk/#register-custom-events
iOS : https://dev.branch.io/references/iOS_sdk/#register-custom-events

**Comment by aaustin** [comment]
Fixed just now!
